apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bankapp-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - webapps
  selector:
    matchLabels:
      app: bankapp
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
