---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secret
  namespace: webapps
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgBxST1sWyoLvRE8uS871yz9nae9ymq3qvVUaqasUST3J9Z7v1x4clM5o1jCI2C5Mp6SCZQjD6/W2goPjbMjKjHRWkX7+4Faei77OH9Yauwmgi8Jty9SG7pHxFDM7AAwN/BIRv8DaUsm7yZmgCa7EGsTYowDmlvfnC2GUlMMs+6eAN0iDOuSocwv/nREsP+PrnwjV/+yQ/ZFKz4p23QeezarbllFzTCyYo5ua6QcTvIhwWllrI5Ej5QDgjrkFjpFTxhjpB3XA6trVlMRQa8cnVKVYFVFyg5aYz0QvLA2npE0Ei0UaEZnOwt9G+tZ4VKxHDDAlPm2g3YjX6C2GU66ocpEqEAczmfSxwufegVebTLNhvdRHFxdx3DaDXHo+0+dQ4Ng+44AhgmQEBPWz3D06a6GXjQ4crhpCNgaziPbHKWnzhyRHNoWe95oStwoYvpvVojD4dl2i3V9VO/9eKzey+CMIsSVNksPCOfWfJYDX8qDE23AprAjLTJ8Aztipqq3Lya7YPjcfl7Pv81WfKKOWVmsCevevTSQznHmt/qLUj1dR6+9cUANUzW8cqiyCTmJt9+E+yBbVbPLH3YJ42EguGgEc/r/U5/Ls5W0cqLmnl4XUfA50r2D3TIPP9KgApqzvsVmdWfGmK1g7q2CtN5J/yQmJD8rD+bLqAvSLJGiJZ8ULA7p4aCXcgM9djXoEJf3YyPTOWdtpeAZxY8=
  template:
    metadata:
      creationTimestamp: null
      name: mysql-secret
      namespace: webapps
